---
- name: Launch EC2 instance
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: "Security group for web server"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: sg_result

    - name: Launch EC2
      amazon.aws.ec2_instance:
        name: "Ansible-EC2"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        count: "{{ count }}"
        wait: true
        vpc_subnet_id: null
        security_groups: ["{{ security_group }}"]
      register: ec2_result

    - name: Debug EC2 result
      debug:
        var: ec2_result

    - name: Add new host to dynamic inventory
      add_host:
        name: "{{ ec2_result.instances[0].public_ip_address }}"
        groups: launched
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/{{ key_name }}.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
