- name: Launch EC2 instance
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: Allow HTTP and SSH
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        state: present

    - name: Launch EC2
      amazon.aws.ec2_instance:
        name: "WebServer"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        wait: yes
        count: "{{ count }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: yes
        tags:
          Name: WebServer
      register: ec2

    - name: Add new host to dynamic inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webservers
      loop: "{{ ec2.instances }}"
